import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './tailwind.css';
import './theme.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Providers from '@/components/Providers';
import ConfettiCelebration from '@/components/ConfettiCelebration';
import PageTransition from '@/components/PageTransition';

const geistSans = Geist({ subsets: ['latin'] });
const geistMono = Geist_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.className} ${geistMono.className} antialiased bg-[var(--bm-bg)] text-[var(--bm-text)]`}
      >
        <Providers>
          <ConfettiCelebration />
          <Header />
          <PageTransition>
            <main className="container mx-auto p-4 min-h-screen">{children}</main>
          </PageTransition>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
