import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'tailwindcss/tailwind.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Providers from '@/components/Providers';
import ConfettiCelebration from '@/components/ConfettiCelebration';

const geistSans = Geist({ subsets: ['latin'] });
const geistMono = Geist_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.className} ${geistMono.className} antialiased bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100`}
      >
        <Providers>
          <ConfettiCelebration />
          <Header />
          <main className="container mx-auto p-4 min-h-screen">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
